config/routes.rb
Rails.application.routes.draw do
  get 'stocks/index'
  get 'stocks/show'
  get 'stocks/search'
  post 'stocks/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/pages/:page" => "pages#show"
  root "pages#show", page: "home"

  resources :admins, only: [:index]
  resources :users, path: "manage/users"
  resources :transactions

  devise_for :admins,
    path: "admins",
    controllers: { 
      confirmations: "admins/confirmations",
      mailer: "admins/mailer",
      passwords: "admins/passwords",
      sessions: "admins/sessions",
      shared: "admins/shared",
      unlocks: "admins/unlocks"
    }

  devise_for :users,
    path: "",
    path_names: {
      sign_in: "login",
      sign_out: "logout",
      sign_up: "register"
    },
    controllers: { 
      confirmations: "users/confirmations",
      mailer: "users/mailer",
      passwords: "users/passwords",
      registrations: "users/registrations",
      sessions: "users/sessions",
      shared: "users/shared",
      unlocks: "users/unlocks"
    }

end

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
    <div class="flash-container">
        <p><%= msg %></p>
    </div>
<% end %>

app/views/shared/_sidebar.html.erb
<div id="sidebar">

  <div id="sidebar-container">

    <a href="/">
        <div class="logo-container">
          <%= image_tag ("logo-medium.png"), id: "logo-img" %>
          <h4>Lupin</h4>
        </div>
    </a>

    <div class="sidebar-nav-container">
      <% if current_admin %>
        <nav>
          <ul>
            <li><%= link_to 'Admins', admins_path, class: "low-contrast" %></li>
            <li><%= link_to 'Users', users_path, class: "low-contrast" %></li>
            <li><%= link_to 'Transactions', transactions_path, class: "low-contrast" %></li>
            <li><%= link_to 'Logout', destroy_admin_session_path, method: :delete, class: "low-contrast" %></li>
          </ul>
        </nav>
      <% elsif current_user.try(:broker?) %>
        <nav>
          <ul>
            <li><%= link_to 'Account', edit_user_registration_path, class: "low-contrast" %></li>
            <li><%= link_to 'Portfolio', stocks_index_path, class: "low-contrast" %></li>
            <li><%= link_to 'Transactions', transactions_path, class: "low-contrast" %></li>
            <li><%= link_to 'Search Stocks', stocks_search_path, class: "low-contrast" %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "low-contrast" %></li>
          </ul>
        </nav>
      <% elsif current_user.try(:buyer?) %>
        <nav>
          <ul>
            <li><%= link_to 'My Account', edit_user_registration_path, class: "low-contrast" %></li>
            <li><%= link_to 'My Portfolio', stocks_path, class: "low-contrast" %></li>
            <li><%= link_to 'Transactions', transactions_path, class: "low-contrast" %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "low-contrast" %></li>
          </ul>
        </nav>
      <% else %>
        <nav>
          <ul>
            <li><%= link_to 'Login', new_user_session_path, class: "low-contrast" %></li>
            <li><%= link_to 'Sign Up', new_user_registration_path, class: "low-contrast" %></li>
            <li><%= link_to 'Admin Login', new_admin_session_path, class: "low-contrast" %></li>
          </ul>
        </nav>
      <% end %>
    </div>

      <p class="tiny low-contrast">Made with Ruby on Rails.</p>

  </div>

</div>