config/routes.rb
Rails.application.routes.draw do
  get 'stocks/index'
  get 'stocks/show'
  get 'stocks/search'
  post 'stocks/create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/pages/:page" => "pages#show"
  root "pages#show", page: "home"

  resources :admins, only: [:index]
  resources :users, path: "manage/users"
  resources :transactions

  devise_for :admins,
    path: "admins",
    controllers: { 
      confirmations: "admins/confirmations",
      mailer: "admins/mailer",
      passwords: "admins/passwords",
      sessions: "admins/sessions",
      shared: "admins/shared",
      unlocks: "admins/unlocks"
    }

  devise_for :users,
    path: "",
    path_names: {
      sign_in: "login",
      sign_out: "logout",
      sign_up: "register"
    },
    controllers: { 
      confirmations: "users/confirmations",
      mailer: "users/mailer",
      passwords: "users/passwords",
      registrations: "users/registrations",
      sessions: "users/sessions",
      shared: "users/shared",
      unlocks: "users/unlocks"
    }

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    @transactions = current_user.transactions.all
    @transactions_all = Transaction.all
  end

  def show
    @transaction = current_user.transactions.find(params[:id])
  end

  def new
    @transaction = current_user.transactions.build
  end

  def create
    @transaction = current_user.transactions.build(transaction_params)
    @transaction.user_id = current_user.id
    @stock = params[:stock_id]
    @transaction.stock_id = @stock.id
    @transaction.broker_id = @stock.user_id
    @transaction.stock_sale_price = @stock.opening_price

    if @Transaction.save
      redirect_to transactions_path, notice: "New Transaction created"
    else
      render :new
    end
  end

  private
    def transaction_params
      params.require(:transaction).permit(:stock_sale_price, :units, :price)
    end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>